WindsorSt/Controllers/BlockController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WindsorSt.Models;

namespace WindsorSt.Controllers
{
    public class BlockController : Controller
    {
        private WindsorStDBContext db = new WindsorStDBContext();

        //
        // GET: /Block/

        public ActionResult Index()
        {
            return View(db.Blocks.ToList());
        }

        //
        // GET: /Block/Details/5

        public ActionResult Details(int id = 0)
        {
            Block block = db.Blocks.Find(id);
            if (block == null)
            {
                return HttpNotFound();
            }
            return View(block);
        }

        //
        // GET: /Block/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Block/Create

        [HttpPost]
        public ActionResult Create(Block block)
        {
            if (ModelState.IsValid)
            {
                db.Blocks.Add(block);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(block);
        }

        //
        // GET: /Block/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Block block = db.Blocks.Find(id);
            if (block == null)
            {
                return HttpNotFound();
            }
            return View(block);
        }

        //
        // POST: /Block/Edit/5

        [HttpPost]
        public ActionResult Edit(Block block)
        {
            if (ModelState.IsValid)
            {
                db.Entry(block).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(block);
        }

        //
        // GET: /Block/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Block block = db.Blocks.Find(id);
            if (block == null)
            {
                return HttpNotFound();
            }
            return View(block);
        }

        //
        // POST: /Block/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Block block = db.Blocks.Find(id);
            db.Blocks.Remove(block);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WindsorSt/Controllers/LayoutLocationController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WindsorSt.Models;

namespace WindsorSt.Controllers
{
    public class LayoutLocationController : Controller
    {
        private WindsorStDBContext db = new WindsorStDBContext();

        //
        // GET: /LayoutLocation/

        public ActionResult Index()
        {
            return View(db.LayoutLocations.ToList());
        }

        //
        // GET: /LayoutLocation/Details/5

        public ActionResult Details(int id = 0)
        {
            LayoutLocation layoutlocation = db.LayoutLocations.Find(id);
            if (layoutlocation == null)
            {
                return HttpNotFound();
            }
            return View(layoutlocation);
        }

        //
        // GET: /LayoutLocation/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /LayoutLocation/Create

        [HttpPost]
        public ActionResult Create(LayoutLocation layoutlocation)
        {
            if (ModelState.IsValid)
            {
                db.LayoutLocations.Add(layoutlocation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(layoutlocation);
        }

        //
        // GET: /LayoutLocation/Edit/5

        public ActionResult Edit(int id = 0)
        {
            LayoutLocation layoutlocation = db.LayoutLocations.Find(id);
            if (layoutlocation == null)
            {
                return HttpNotFound();
            }
            return View(layoutlocation);
        }

        //
        // POST: /LayoutLocation/Edit/5

        [HttpPost]
        public ActionResult Edit(LayoutLocation layoutlocation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(layoutlocation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(layoutlocation);
        }

        //
        // GET: /LayoutLocation/Delete/5

        public ActionResult Delete(int id = 0)
        {
            LayoutLocation layoutlocation = db.LayoutLocations.Find(id);
            if (layoutlocation == null)
            {
                return HttpNotFound();
            }
            return View(layoutlocation);
        }

        //
        // POST: /LayoutLocation/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            LayoutLocation layoutlocation = db.LayoutLocations.Find(id);
            db.LayoutLocations.Remove(layoutlocation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WindsorSt/Controllers/TrainTypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WindsorSt.Models;

namespace WindsorSt.Controllers
{
    public class TrainTypesController : Controller
    {
        private WindsorStDBContext db = new WindsorStDBContext();

        //
        // GET: /TrainTypes/

        public ActionResult Index()
        {
            return View(db.TrainTypes.ToList());
        }

        //
        // GET: /TrainTypes/Details/5

        public ActionResult Details(int id = 0)
        {
            TrainType traintype = db.TrainTypes.Find(id);
            if (traintype == null)
            {
                return HttpNotFound();
            }
            return View(traintype);
        }

        //
        // GET: /TrainTypes/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /TrainTypes/Create

        [HttpPost]
        public ActionResult Create(TrainType traintype)
        {
            if (ModelState.IsValid)
            {
                db.TrainTypes.Add(traintype);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(traintype);
        }

        //
        // GET: /TrainTypes/Edit/5

        public ActionResult Edit(int id = 0)
        {
            TrainType traintype = db.TrainTypes.Find(id);
            if (traintype == null)
            {
                return HttpNotFound();
            }
            return View(traintype);
        }

        //
        // POST: /TrainTypes/Edit/5

        [HttpPost]
        public ActionResult Edit(TrainType traintype)
        {
            if (ModelState.IsValid)
            {
                db.Entry(traintype).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(traintype);
        }

        //
        // GET: /TrainTypes/Delete/5

        public ActionResult Delete(int id = 0)
        {
            TrainType traintype = db.TrainTypes.Find(id);
            if (traintype == null)
            {
                return HttpNotFound();
            }
            return View(traintype);
        }

        //
        // POST: /TrainTypes/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            TrainType traintype = db.TrainTypes.Find(id);
            db.TrainTypes.Remove(traintype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

WindsorSt/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>

                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("Blocks", "Index", "Block")</li>
                        <li>@Html.ActionLink("Cars", "Index", "Cars")</li>
                        <li>@Html.ActionLink("Industries", "Index", "Industries")</li>
                        <li>@Html.ActionLink("Layout Locations", "Index", "LayoutLocation")</li>
                        <li>@Html.ActionLink("Locomotives", "Index", "Locomotives")</li>
                        <li>@Html.ActionLink("Locomotive Statuses", "Index", "LocomotiveStatuses")</li>
                        <li>@Html.ActionLink("Off Layout Destinations", "Index", "OfflayoutDestinations")</li>
                        <li>@Html.ActionLink("Trains", "Index", "Trains")</li>
                        <li>@Html.ActionLink("Train Types", "Index", "TrainTypes")</li>

</ul> 
      @*                  <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
      *@              </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>